### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'winmode

### ISSUE THREAD

**Issue by james1kobby** [acados/acados#1041]
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    run_nominal_control(chain_params)
  File "/home/ubuntu/Code_Study/acados/examples/acados_python/chain_mass/run_nominal_control.py", line 196, in run_nominal_control
    acados_integrator = export_chain_mass_integrator(n_mass, m, D, L)
  File "/home/ubuntu/Code_Study/acados/examples/acados_python/chain_mass/export_chain_mass_integrator.py", line 78, in export_chain_mass_integrator
    acados_integrator = AcadosSimSolver(sim, json_file = 'acados_ocp_' + model.name + '.json')
  File "/home/ubuntu/Code_Study/acados/interfaces/acados_template/acados_template/acados_sim_solver.py", line 272, in __init__
    self.__acados_lib = DllLoader(libacados_filepath, winmode=self.winmode)
TypeError: __init__() got an unexpected keyword argument 'winmode

**Comment by james1kobby** [comment]
File "/home/ubuntu/Code_Study/acados/interfaces/acados_template/acados_template/acados_sim_solver.py", line 272, in init
self.__acados_lib = DllLoader(libacados_filepath, winmode=self.winmode)


修改成
File "/home/ubuntu/Code_Study/acados/interfaces/acados_template/acados_template/acados_sim_solver.py", line 272, in init
self.__acados_lib = DllLoader(libacados_filepath)

因为winmode=self.winmode时windows系统上加载动态库的标志

**Comment by FreyJo** [comment]
what version of ctypes do you have?

**Comment by james1kobby** [comment]
@FreyJo ，I don't know, how to updating ctypes？ I use python virtualenv to install ctypes.  
can yu tell me? thank you  very much.

**Comment by FreyJo** [comment]
I am not sure. I think the ctypes version needed is not that recent.
What python version do you use? Could just update that?

**Comment by FreyJo** [comment]
I fixed this in https://github.com/acados/acados/pull/1101
