### ISSUE TITLE
Exception: acados -- mismatching dimensions

### ISSUE THREAD

**Issue by mariuszjaniak** [acados/acados#578]
Recently the python getting started example has been broken 
```
Traceback (most recent call last):
  File "minimal_example_closed_loop.py", line 109, in <module>
    acados_ocp_solver = AcadosOcpSolver(ocp, json_file = 'acados_ocp_' + model.name + '.json')
  File "/home/mjaniak/.local/lib/python3.5/site-packages/acados_template/acados_ocp_solver.py", line 393, in __init__
    ocp_formulation_json_dump(acados_ocp, json_file)
  File "/home/mjaniak/.local/lib/python3.5/site-packages/acados_template/acados_ocp_solver.py", line 183, in ocp_formulation_json_dump
    ocp_check_json_against_layout(ocp_nlp_dict, dims_dict)
  File "/home/mjaniak/.local/lib/python3.5/site-packages/acados_template/utils.py", line 262, in ocp_check_json_against_layout
    ocp_check_json_against_layout_recursion(ocp_nlp, ocp_dims, ocp_nlp_layout)
  File "/home/mjaniak/.local/lib/python3.5/site-packages/acados_template/utils.py", line 272, in ocp_check_json_against_layout_recursion
    item = ocp_check_json_against_layout_recursion(item, ocp_dims, ocp_nlp_layout[key])
  File "/home/mjaniak/.local/lib/python3.5/site-packages/acados_template/utils.py", line 300, in ocp_check_json_against_layout_recursion
    .format(key, item_dims, dim_names, dims))
Exception: acados -- mismatching dimensions for field W. Provided data has dimensions (5, 5), while associated dimensions ['ny', 'ny'] are (0, 0)
Exception ignored in: <bound method AcadosOcpSolver.__del__ of <acados_template.acados_ocp_solver.AcadosOcpSolver object at 0x7f24147a49e8>>
Traceback (most recent call last):
  File "/home/mjaniak/.local/lib/python3.5/site-packages/acados_template/acados_ocp_solver.py", line 737, in __del__
    self.shared_lib.acados_free()
AttributeError: 'AcadosOcpSolver' object has no attribute 'shared_lib'
```
This has fixed the problem 
```
diff --git a/examples/acados_python/getting_started/minimal_example_closed_loop.py b/examples/acados_python/getting_started/minimal_example_closed_loop.py
index 020ad401..687387cd 100644
--- a/examples/acados_python/getting_started/minimal_example_closed_loop.py
+++ b/examples/acados_python/getting_started/minimal_example_closed_loop.py
@@ -58,11 +58,11 @@ N = 20
 ocp.dims.N = N
 # NOTE: all dimensions but N are now detected automatically in the
 #   Python interface, i.e. the following is redundant:
-# ocp.dims.nx  = nx
-# ocp.dims.ny  = ny
-# ocp.dims.ny_e = ny_e
-# ocp.dims.nbu = nu
-# ocp.dims.nu  = nu
+ocp.dims.nx  = nx
+ocp.dims.ny  = ny
+ocp.dims.ny_e = ny_e
+ocp.dims.nbu = nu
+ocp.dims.nu  = nu
 
 # set cost module
 ocp.cost.cost_type = 'LINEAR_LS'
-- 
2.26.0
```

**Comment by FreyJo** [comment]
Hi,
first of all, thanks for reporting.
The example is not broken though, instead the Python interface has been changed, such that
`all dimensions but N are now detected automatically`.

Please install the Python package acados_template from the latest version.

Note: you can install it symbolically with `-e` such that you dont have to reinstall after switching acados versions, i.e.
```
pip install -e  <acados_root_folder>/interfaces/acados_template
```
