### ISSUE TITLE
ValueError when I change the value of ocp.dims.N

### ISSUE THREAD

**Issue by 17150934** [acados/acados#748]
Hi,when I change the value of ocp.dims.N from 20 to 40 in the acados/examples/acados_python/getting_started/ocp/minimal_example_ocp.py

```
import sys
sys.path.insert(0, '../common')

from acados_template import AcadosOcp, AcadosOcpSolver
from pendulum_model import export_pendulum_ode_model
import numpy as np
import scipy.linalg
from utils import plot_pendulum

# create ocp object to formulate the OCP
ocp = AcadosOcp()

# set model
model = export_pendulum_ode_model()
ocp.model = model

Tf = 1.0
nx = model.x.size()[0]
nu = model.u.size()[0]
ny = nx + nu
ny_e = nx
N = 40 (Originally 20)

# set dimensions
ocp.dims.N = N
```
it produced a valueError：
```
Traceback (most recent call last):

  File "<ipython-input-9-691c69ccf0a8>", line 1, in <module>
    runfile('/home/vcdc/acados/examples/acados_python/getting_started/ocp/minimal_example_ocp.py', wdir='/home/vcdc/acados/examples/acados_python/getting_started/ocp')

  File "/home/vcdc/anaconda3/envs/flow/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/vcdc/anaconda3/envs/flow/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/vcdc/acados/examples/acados_python/getting_started/ocp/minimal_example_ocp.py", line 121, in <module>
    simU[i,:] = ocp_solver.get(i, "u")

ValueError: could not broadcast input array from shape (0,) into shape (1,)
```
why it happened?

**Comment by FreyJo** [comment]
Duplicated from discourse.acados.org
Please submit similar questions only there.
