### ISSUE TITLE
problem of python Installation

### ISSUE THREAD

**Issue by johnwaneboy** [acados/acados#818]
when i  run a Python example to check if everything works. I get started with the example <acados_root>/examples/acados_python/getting_started/ocp/minimal_example_ocp.py. 
I get the below error 
(env) wane@wane:~/acados/examples/acados_python/getting_started/ocp$ python3.7 minimal_example_ocp.py
Segmentation fault
Traceback (most recent call last):
  File "minimal_example_ocp.py", line 102, in <module>
    ocp_solver = AcadosOcpSolver(ocp, json_file = 'acados_ocp.json')
  File "/home/wane/acados/interfaces/acados_template/acados_template/acados_ocp_solver.py", line 924, in __init__
    self.generate(acados_ocp, json_file=json_file, simulink_opts=simulink_opts, cmake_builder=cmake_builder)
  File "/home/wane/acados/interfaces/acados_template/acados_template/acados_ocp_solver.py", line 868, in generate
    ocp_render_templates(acados_ocp, json_file, cmake_builder=cmake_builder)
  File "/home/wane/acados/interfaces/acados_template/acados_template/acados_ocp_solver.py", line 685, in ocp_render_templates
    render_template(in_file, out_file, template_dir, json_path)
  File "/home/wane/acados/interfaces/acados_template/acados_template/utils.py", line 223, in render_template
    raise Exception(f'Rendering of {in_file} failed!\n\nAttempted to execute OS command:\n{os_cmd}\n.\n')
Exception: Rendering of main.in.c failed!

Attempted to execute OS command:
/home/wane/acados/bin/t_renderer '/home/wane/acados/interfaces/acados_template/acados_template/c_templates_tera/*' 'main.in.c' '/home/wane/acados/examples/acados_python/getting_started/ocp/acados_ocp.json' 'main_pendulum_ode.c'
.

**Comment by FreyJo** [comment]
will be further discussed here:
https://discourse.acados.org/t/problem-of-installing-python-python-interface/757/2
