### ISSUE TITLE
Problem running time_optimal_example.py

### ISSUE THREAD

**Issue by sdfzz** [acados/acados#844]
Hi all,

Sorry for asking yet another question. I've been trying to use cython to speed up the optimization.

I trying to run acados/examples/acados_python/crane/time_optimal_example.py, and I'm getting the error attached below:

I can run other python codes and examples (such as acados/examples/acados_python/getting_started/ocp/minimal_example_ocp.py) without any problems...

My environment is:
Ubuntu 18.04
Python 3.7.5
virtual environment

Any help would be greatly appreciated

Steve

ERROR:

(python3) root@zenbook-ZenBook-Pro-Duo-UX581GV-UX581GV:~/acados/examples/acados_python/crane# python time_optimal_example.py 
rm -f libacados_ocp_solver_crane_time_opt.so
rm -f acados_solver_crane_time_opt.o
rm -f acados_ocp_solver_pyx.so
rm -f acados_ocp_solver_pyx.o
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/root/acados/include -I/root/acados/include/acados -I/root/acados/include/blasfeo/include -I/root/acados/include/hpipm/include -I /root/acados/include/qpOASES_e/  -c -o crane_time_opt_cost/crane_time_opt_cost_ext_cost_0_fun.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_0_fun.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/root/acados/include -I/root/acados/include/acados -I/root/acados/include/blasfeo/include -I/root/acados/include/hpipm/include -I /root/acados/include/qpOASES_e/  -c -o crane_time_opt_cost/crane_time_opt_cost_ext_cost_0_fun_jac.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_0_fun_jac.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/root/acados/include -I/root/acados/include/acados -I/root/acados/include/blasfeo/include -I/root/acados/include/hpipm/include -I /root/acados/include/qpOASES_e/  -c -o crane_time_opt_cost/crane_time_opt_cost_ext_cost_0_fun_jac_hess.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_0_fun_jac_hess.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/root/acados/include -I/root/acados/include/acados -I/root/acados/include/blasfeo/include -I/root/acados/include/hpipm/include -I /root/acados/include/qpOASES_e/  -c -o crane_time_opt_cost/crane_time_opt_cost_ext_cost_fun.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_fun.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/root/acados/include -I/root/acados/include/acados -I/root/acados/include/blasfeo/include -I/root/acados/include/hpipm/include -I /root/acados/include/qpOASES_e/  -c -o crane_time_opt_cost/crane_time_opt_cost_ext_cost_fun_jac.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_fun_jac.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/root/acados/include -I/root/acados/include/acados -I/root/acados/include/blasfeo/include -I/root/acados/include/hpipm/include -I /root/acados/include/qpOASES_e/  -c -o crane_time_opt_cost/crane_time_opt_cost_ext_cost_fun_jac_hess.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_fun_jac_hess.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/root/acados/include -I/root/acados/include/acados -I/root/acados/include/blasfeo/include -I/root/acados/include/hpipm/include -I /root/acados/include/qpOASES_e/  -c -o crane_time_opt_cost/crane_time_opt_cost_ext_cost_e_fun.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_e_fun.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/root/acados/include -I/root/acados/include/acados -I/root/acados/include/blasfeo/include -I/root/acados/include/hpipm/include -I /root/acados/include/qpOASES_e/  -c -o crane_time_opt_cost/crane_time_opt_cost_ext_cost_e_fun_jac.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_e_fun_jac.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/root/acados/include -I/root/acados/include/acados -I/root/acados/include/blasfeo/include -I/root/acados/include/hpipm/include -I /root/acados/include/qpOASES_e/  -c -o crane_time_opt_cost/crane_time_opt_cost_ext_cost_e_fun_jac_hess.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_e_fun_jac_hess.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/root/acados/include -I/root/acados/include/acados -I/root/acados/include/blasfeo/include -I/root/acados/include/hpipm/include -I /root/acados/include/qpOASES_e/  -c -o acados_solver_crane_time_opt.o acados_solver_crane_time_opt.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/root/acados/include -I/root/acados/include/acados -I/root/acados/include/blasfeo/include -I/root/acados/include/hpipm/include -I /root/acados/include/qpOASES_e/  -c -o crane_time_opt_model/crane_time_opt_expl_ode_fun.o crane_time_opt_model/crane_time_opt_expl_ode_fun.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/root/acados/include -I/root/acados/include/acados -I/root/acados/include/blasfeo/include -I/root/acados/include/hpipm/include -I /root/acados/include/qpOASES_e/  -c -o crane_time_opt_model/crane_time_opt_expl_vde_forw.o crane_time_opt_model/crane_time_opt_expl_vde_forw.c
cc -fPIC -std=c99   -O2 -DACADOS_WITH_QPOASES -I/root/acados/include -I/root/acados/include/acados -I/root/acados/include/blasfeo/include -I/root/acados/include/hpipm/include -I /root/acados/include/qpOASES_e/  -c -o crane_time_opt_model/crane_time_opt_expl_ode_hess.o crane_time_opt_model/crane_time_opt_expl_ode_hess.c
cc -shared crane_time_opt_cost/crane_time_opt_cost_ext_cost_0_fun.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_0_fun_jac.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_0_fun_jac_hess.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_fun.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_fun_jac.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_fun_jac_hess.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_e_fun.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_e_fun_jac.o crane_time_opt_cost/crane_time_opt_cost_ext_cost_e_fun_jac_hess.o acados_solver_crane_time_opt.o crane_time_opt_model/crane_time_opt_expl_ode_fun.o crane_time_opt_model/crane_time_opt_expl_vde_forw.o crane_time_opt_model/crane_time_opt_expl_ode_hess.o -o libacados_ocp_solver_crane_time_opt.so -L/root/acados/lib -lacados -lhpipm -lblasfeo -lm -lqpOASES_e \
-L -l
cython \
-o acados_ocp_solver_pyx.c \
-I /root/acados/include/../interfaces/acados_template/acados_template \
/root/acados/include/../interfaces/acados_template/acados_template/acados_ocp_solver_pyx.pyx \
-I /root/acados/examples/acados_python/crane/c_generated_code \

cc  -c -O2 \
-fPIC \
-o acados_ocp_solver_pyx.o \
-I /usr/include/python3.8 \
-I /root/acados/include/blasfeo/include/ \
-I /root/acados/include/hpipm/include/ \
-I /root/acados/include \
-I /root/python3/lib/python3.7/site-packages/numpy/core/include \
acados_ocp_solver_pyx.c \

acados_ocp_solver_pyx.c:6:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
compilation terminated.
Makefile:151: recipe for target 'ocp_cython_o' failed
make: *** [ocp_cython_o] Error 1
Traceback (most recent call last):
  File "time_optimal_example.py", line 233, in <module>
    main(use_cython=use_cython)
  File "time_optimal_example.py", line 126, in main
    ocp_solver = AcadosOcpSolver.create_cython_solver('acados_ocp.json')
  File "/root/acados/interfaces/acados_template/acados_template/acados_ocp_solver.py", line 909, in create_cython_solver
    acados_ocp_solver_pyx = importlib.import_module(f'{rel_code_export_directory}.acados_ocp_solver_pyx')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'c_generated_code.acados_ocp_solver_pyx'

**Comment by sdfzz** [comment]
Ok I fixed the problem

It seems that there was some find of conflicts in my Python setting

I ended up re-installing Ubuntu, and now I can run the code without any issue

cheers

Steve
