### ISSUE TITLE
Problem when running minimal_example_ocp.py

### ISSUE THREAD

**Issue by LeeWenX** [acados/acados#870]
Hi,
I am trying to run the example /examples/acados_python/getting_started/ocp/minimal_example_ocp.py, but I get the error blow:

Traceback (most recent call last):
  File "minimal_example_ocp.py", line 89, in <module>
    ocp_solver = AcadosOcpSolver(ocp, json_file = 'acados_ocp.json')
  File "/home/xlw/acados/interfaces/acados_template/acados_template/acados_ocp_solver.py", line 953, in __init__
    self.__acados_lib = CDLL(libacados_filepath)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/xlw/acados/lib/libacados.so: undefined symbol: QProblem_init

Any help will be apreciate!
Thanks!

**Comment by LeeWenX** [comment]
It works. Thanks for your help!!!
